name: Documentation
on: [pull_request]
permissions:
  contents: read
jobs:
  check-links:
    uses: mikavilpas/dotfiles/.github/workflows/docs.yml@8cc49b8e27bd5535cdd607fd9b98fa68a1e3d0ac # main
    secrets: inherit
